{{ config(materialized='table') }}
SELECT
SA.SALES_AGENT_ID,
SA.NAME AS AGENT_NAME,
SUM((SA.SALEC_COMMISION_PCT*ORD.PURCHASE_AMT)::number(32,2))COMMISION_EARNED
FROM
VATSAV_DB.SALES_SCHEMA.SALES_AGENT AS SA
INNER JOIN VATSAV_DB.SALES_SCHEMA.ORDERS ORD
ON ORD.SALES_AGENT_ID =SA.SALES_AGENT_ID
GROUP BY 1,2